package com.pavarenkin.vip_lab.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pavarenkin.vip_lab.db.Flex;
import com.pavarenkin.vip_lab.db.User;
import com.pavarenkin.vip_lab.db.Repo;
import com.pavarenkin.vip_lab.db.Note;
import com.pavarenkin.vip_lab.db.Post;

import com.pavarenkin.vip_lab.db.FlexDao;
import com.pavarenkin.vip_lab.db.UserDao;
import com.pavarenkin.vip_lab.db.RepoDao;
import com.pavarenkin.vip_lab.db.NoteDao;
import com.pavarenkin.vip_lab.db.PostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig flexDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig repoDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig postDaoConfig;

    private final FlexDao flexDao;
    private final UserDao userDao;
    private final RepoDao repoDao;
    private final NoteDao noteDao;
    private final PostDao postDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        flexDaoConfig = daoConfigMap.get(FlexDao.class).clone();
        flexDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repoDaoConfig = daoConfigMap.get(RepoDao.class).clone();
        repoDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        flexDao = new FlexDao(flexDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        repoDao = new RepoDao(repoDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);

        registerDao(Flex.class, flexDao);
        registerDao(User.class, userDao);
        registerDao(Repo.class, repoDao);
        registerDao(Note.class, noteDao);
        registerDao(Post.class, postDao);
    }
    
    public void clear() {
        flexDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        repoDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        postDaoConfig.clearIdentityScope();
    }

    public FlexDao getFlexDao() {
        return flexDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RepoDao getRepoDao() {
        return repoDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

}
