package com.pavarenkin.vip_lab.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pavarenkin.vip_lab.db.FlexPicture;
import com.pavarenkin.vip_lab.db.Flex;
import com.pavarenkin.vip_lab.db.FlexState;
import com.pavarenkin.vip_lab.db.User;
import com.pavarenkin.vip_lab.db.Repo;
import com.pavarenkin.vip_lab.db.Post;

import com.pavarenkin.vip_lab.db.FlexPictureDao;
import com.pavarenkin.vip_lab.db.FlexDao;
import com.pavarenkin.vip_lab.db.FlexStateDao;
import com.pavarenkin.vip_lab.db.UserDao;
import com.pavarenkin.vip_lab.db.RepoDao;
import com.pavarenkin.vip_lab.db.PostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig flexPictureDaoConfig;
    private final DaoConfig flexDaoConfig;
    private final DaoConfig flexStateDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig repoDaoConfig;
    private final DaoConfig postDaoConfig;

    private final FlexPictureDao flexPictureDao;
    private final FlexDao flexDao;
    private final FlexStateDao flexStateDao;
    private final UserDao userDao;
    private final RepoDao repoDao;
    private final PostDao postDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        flexPictureDaoConfig = daoConfigMap.get(FlexPictureDao.class).clone();
        flexPictureDaoConfig.initIdentityScope(type);

        flexDaoConfig = daoConfigMap.get(FlexDao.class).clone();
        flexDaoConfig.initIdentityScope(type);

        flexStateDaoConfig = daoConfigMap.get(FlexStateDao.class).clone();
        flexStateDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        repoDaoConfig = daoConfigMap.get(RepoDao.class).clone();
        repoDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        flexPictureDao = new FlexPictureDao(flexPictureDaoConfig, this);
        flexDao = new FlexDao(flexDaoConfig, this);
        flexStateDao = new FlexStateDao(flexStateDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        repoDao = new RepoDao(repoDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);

        registerDao(FlexPicture.class, flexPictureDao);
        registerDao(Flex.class, flexDao);
        registerDao(FlexState.class, flexStateDao);
        registerDao(User.class, userDao);
        registerDao(Repo.class, repoDao);
        registerDao(Post.class, postDao);
    }
    
    public void clear() {
        flexPictureDaoConfig.clearIdentityScope();
        flexDaoConfig.clearIdentityScope();
        flexStateDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        repoDaoConfig.clearIdentityScope();
        postDaoConfig.clearIdentityScope();
    }

    public FlexPictureDao getFlexPictureDao() {
        return flexPictureDao;
    }

    public FlexDao getFlexDao() {
        return flexDao;
    }

    public FlexStateDao getFlexStateDao() {
        return flexStateDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RepoDao getRepoDao() {
        return repoDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

}
