package com.pavarenkin.vip_lab.db;

import org.greenrobot.greendao.annotation.*;

import com.pavarenkin.vip_lab.domain.enums.Action;
import com.pavarenkin.vip_lab.domain.enums.Kind;
import com.pavarenkin.vip_lab.domain.enums.State;
import com.pavarenkin.vip_lab.domain.enums.Status;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FLEX_PICTURE".
 */
@Entity
public class FlexPicture {

    @Id(autoincrement = true)
    private Long id;

    @Convert(converter = com.pavarenkin.vip_lab.domain.converters.KindConverter.class, columnType = String.class)
    @NotNull
    private Kind kind;

    @Convert(converter = com.pavarenkin.vip_lab.domain.converters.StateConverter.class, columnType = String.class)
    @NotNull
    private State state;

    @Convert(converter = com.pavarenkin.vip_lab.domain.converters.ActionConverter.class, columnType = String.class)
    @NotNull
    private Action action;

    @Convert(converter = com.pavarenkin.vip_lab.domain.converters.StatusConverter.class, columnType = String.class)
    @NotNull
    private Status status;
    private String picture;
    private String comment;
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public FlexPicture() {
    }

    public FlexPicture(Long id) {
        this.id = id;
    }

    @Generated
    public FlexPicture(Long id, Kind kind, State state, Action action, Status status, String picture, String comment, java.util.Date date) {
        this.id = id;
        this.kind = kind;
        this.state = state;
        this.action = action;
        this.status = status;
        this.picture = picture;
        this.comment = comment;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public Kind getKind() {
        return kind;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKind(@NotNull Kind kind) {
        this.kind = kind;
    }

    @NotNull
    public State getState() {
        return state;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setState(@NotNull State state) {
        this.state = state;
    }

    @NotNull
    public Action getAction() {
        return action;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAction(@NotNull Action action) {
        this.action = action;
    }

    @NotNull
    public Status getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(@NotNull Status status) {
        this.status = status;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
