package com.pavarenkin.vip_lab.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MENU".
 */
@Entity
public class Menu {

    @Id(autoincrement = true)
    private Long id;
    private int kind;
    private int icon;

    @NotNull
    private String name;
    private String uuid;
    private Integer action;
    private Integer number;
    private Integer state;
    private String hash;
    private String json;
    private String caption;
    private Integer image;
    private Integer color;
    private Integer fontcolor;
    private Integer knowledge;
    private Integer training;
    private Integer education;
    private Integer experience;
    private Integer favorite;
    private Integer sound;
    private String audio;
    private Integer parent;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Menu() {
    }

    public Menu(Long id) {
        this.id = id;
    }

    @Generated
    public Menu(Long id, int kind, int icon, String name, String uuid, Integer action, Integer number, Integer state, String hash, String json, String caption, Integer image, Integer color, Integer fontcolor, Integer knowledge, Integer training, Integer education, Integer experience, Integer favorite, Integer sound, String audio, Integer parent) {
        this.id = id;
        this.kind = kind;
        this.icon = icon;
        this.name = name;
        this.uuid = uuid;
        this.action = action;
        this.number = number;
        this.state = state;
        this.hash = hash;
        this.json = json;
        this.caption = caption;
        this.image = image;
        this.color = color;
        this.fontcolor = fontcolor;
        this.knowledge = knowledge;
        this.training = training;
        this.education = education;
        this.experience = experience;
        this.favorite = favorite;
        this.sound = sound;
        this.audio = audio;
        this.parent = parent;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getKind() {
        return kind;
    }

    public void setKind(int kind) {
        this.kind = kind;
    }

    public int getIcon() {
        return icon;
    }

    public void setIcon(int icon) {
        this.icon = icon;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Integer getAction() {
        return action;
    }

    public void setAction(Integer action) {
        this.action = action;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public Integer getImage() {
        return image;
    }

    public void setImage(Integer image) {
        this.image = image;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public Integer getFontcolor() {
        return fontcolor;
    }

    public void setFontcolor(Integer fontcolor) {
        this.fontcolor = fontcolor;
    }

    public Integer getKnowledge() {
        return knowledge;
    }

    public void setKnowledge(Integer knowledge) {
        this.knowledge = knowledge;
    }

    public Integer getTraining() {
        return training;
    }

    public void setTraining(Integer training) {
        this.training = training;
    }

    public Integer getEducation() {
        return education;
    }

    public void setEducation(Integer education) {
        this.education = education;
    }

    public Integer getExperience() {
        return experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    public Integer getFavorite() {
        return favorite;
    }

    public void setFavorite(Integer favorite) {
        this.favorite = favorite;
    }

    public Integer getSound() {
        return sound;
    }

    public void setSound(Integer sound) {
        this.sound = sound;
    }

    public String getAudio() {
        return audio;
    }

    public void setAudio(String audio) {
        this.audio = audio;
    }

    public Integer getParent() {
        return parent;
    }

    public void setParent(Integer parent) {
        this.parent = parent;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
