package com.pavarenkin.vip_lab.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "POST".
 */
@Entity
public class Post {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String text;
    private Integer value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Post() {
    }

    public Post(Long id) {
        this.id = id;
    }

    @Generated
    public Post(Long id, String text, Integer value) {
        this.id = id;
        this.text = text;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(@NotNull String text) {
        this.text = text;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
